platform :ios, "7.0"

pod 'pop'
pod 'libHN'
pod 'Shimmer'
pod 'iOS-blur'
pod 'ionicons'
pod 'ADNLogin'
pod 'PocketAPI'
pod 'OvershareKit'
pod 'AFNetworking'
pod 'Reachability'
pod 'SVPullToRefresh'
pod 'MCSwipeTableViewCell'
pod 'GTScrollNavigationBar'
pod 'GoogleAnalytics-iOS-SDK'
pod 'CRToast', :git => 'https://github.com/vIiRuS/CRToast.git', :commit => 'e85576e81d'